name = "PowerModelsRestoration"
uuid = "23adbb12-a187-11e9-26a2-eb4d4e6e68fb"
authors = ["David M Fobes <dfobes@lanl.gov>", "Noah Rhodes"]
version = "0.1.0"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsMLD = "b04da1f8-93b0-5a19-8500-8b2903949876"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
InfrastructureModels = "~0.3"
JuMP = "~0.19.1, ~0.20"
MathOptInterface = "~0.8, ~0.9"
Memento = "~0.10, ~0.11, ~0.12"
PowerModels = "~0.13"
julia = "^1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "Cbc", "Juniper"]
